version: "3.3"

services:
        react:
                container_name: dev_client 
                image: skyprecision_client_dev 
                build:
                        context: .
                        dockerfile: Dockerfile.dev
                volumes:
                        - '.:/app'
                ports:
                        - "3000:3000"
                environment:
                        - CHOKIDAR_USEPOLLING=true
