version: "3.3"

services:
        react:
                container_name: test_client
                build: .
                command: npm start
                volumes:
                        - .:/app
                ports:
                        - "3000:3000"
